// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'post_dan.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

PostDan _$PostDanFromJson(Map<String, dynamic> json) {
  return PostDan(
      json['id'] as int,
      json['created_at'] as String,
      json['uploader_id'] as int,
      json['score'] as int,
      json['source'] as String,
      json['md5'] as String,
      json['rating'] as String,
      json['image_width'] as int,
      json['image_height'] as int,
      json['tag_string'] as String,
      json['is_note_locked'] as bool,
      json['fav_count'] as int,
      json['file_ext'] as String,
      json['is_rating_locked'] as bool,
      json['parent_id'] as int,
      json['has_children'] as bool,
      json['tag_count_general'] as int,
      json['tag_count_artist'] as int,
      json['tag_count_character'] as int,
      json['tag_count_copyright'] as int,
      json['file_size'] as int,
      json['is_status_locked'] as bool,
      json['pool_string'] as String,
      json['up_score'] as int,
      json['down_score'] as int,
      json['is_pending'] as bool,
      json['is_flagged'] as bool,
      json['is_deleted'] as bool,
      json['tag_count'] as int,
      json['updated_at'] as String,
      json['is_banned'] as bool,
      json['pixiv_id'] as int,
      json['has_active_children'] as bool,
      json['bit_flags'] as int,
      json['tag_count_meta'] as int,
      json['uploader_name'] as String,
      json['has_large'] as bool,
      json['has_visible_children'] as bool,
      json['children_ids'] as String,
      json['is_favorited'] as bool,
      json['tag_string_general'] as String,
      json['tag_string_character'] as String,
      json['tag_string_copyright'] as String,
      json['tag_string_artist'] as String,
      json['tag_string_meta'] as String,
      json['file_url'] as String,
      json['large_file_url'] as String,
      json['preview_file_url'] as String);
}

Map<String, dynamic> _$PostDanToJson(PostDan instance) => <String, dynamic>{
      'id': instance.id,
      'created_at': instance.createdAt,
      'uploader_id': instance.uploaderId,
      'score': instance.score,
      'source': instance.source,
      'md5': instance.md5,
      'rating': instance.rating,
      'image_width': instance.imageWidth,
      'image_height': instance.imageHeight,
      'tag_string': instance.tagString,
      'is_note_locked': instance.isNoteLocked,
      'fav_count': instance.favCount,
      'file_ext': instance.fileExt,
      'is_rating_locked': instance.isRatingLocked,
      'parent_id': instance.parentId,
      'has_children': instance.hasChildren,
      'tag_count_general': instance.tagCountGeneral,
      'tag_count_artist': instance.tagCountArtist,
      'tag_count_character': instance.tagCountCharacter,
      'tag_count_copyright': instance.tagCountCopyright,
      'file_size': instance.fileSize,
      'is_status_locked': instance.isStatusLocked,
      'pool_string': instance.poolString,
      'up_score': instance.upScore,
      'down_score': instance.downScore,
      'is_pending': instance.isPending,
      'is_flagged': instance.isFlagged,
      'is_deleted': instance.isDeleted,
      'tag_count': instance.tagCount,
      'updated_at': instance.updatedAt,
      'is_banned': instance.isBanned,
      'pixiv_id': instance.pixivId,
      'has_active_children': instance.hasActiveChildren,
      'bit_flags': instance.bitFlags,
      'tag_count_meta': instance.tagCountMeta,
      'uploader_name': instance.uploaderName,
      'has_large': instance.hasLarge,
      'has_visible_children': instance.hasVisibleChildren,
      'children_ids': instance.childrenIds,
      'is_favorited': instance.isFavorited,
      'tag_string_general': instance.tagStringGeneral,
      'tag_string_character': instance.tagStringCharacter,
      'tag_string_copyright': instance.tagStringCopyright,
      'tag_string_artist': instance.tagStringArtist,
      'tag_string_meta': instance.tagStringMeta,
      'file_url': instance.fileUrl,
      'large_file_url': instance.largeFileUrl,
      'preview_file_url': instance.previewFileUrl
    };
